### ISSUE TITLE
Many important files missing

### ISSUE THREAD

**Issue by PytaichukBohdan** [shivam13juna/Quick_Image_Matting_remove.bg_equivalent#2]
Hello!

When I try to run the "app.py.ipynb" notebook, there are lots of crucial files/modules missing.
Like matting, image_slicer. 

Where can I get them?

Thanks in advance

**Comment by shivam13juna** [comment]
hey man, I've assumed you already have a residue image ( that black and
white) generated from some model (many available online). Once you have
those, you can use my notebook.

**Comment by PytaichukBohdan** [comment]
@shivam13juna it's not about black & white

In the starting cell, you import:
`from matting import alpha_matting, load_image, save_image, estimate_foreground_background, stack_images`

Those are the modules responsible for the main manipulations of original and black&white image.
But those modules are absent and are not available to install from pip.
Also, there's no reference to where to clone them from GitHub.

Would be much appreciated if you could provide this extra information :)
Otherwise, the repo is not in the working condition

**Comment by shivam13juna** [comment]
You can find that library from https://github.com/99991/matting

**Comment by PytaichukBohdan** [comment]
Thanks!
